[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --timeout 120 --workers 2 --threads 4 --worker-class gthread --bind 0.0.0.0:$PORT"
